/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.gson)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.scratchgame.App"
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "org.scratchgame.App"
        )
    }
    // Inclui as dependências no JAR para que possa ser executado como um fat JAR
    from(sourceSets.main.get().output)

    // Adiciona as dependências no JAR
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })

    // Configura a estratégia de duplicatas para ignorar ou substituir entradas duplicadas
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}